{
	"swagger": "2.0",
	"info": {
		"title": "Home Connect API",
		"description": "This API provides access to home appliances enabled by Home Connect\n(https://home-connect.com). Through the API programs can be started and\nstopped, or home appliances configured and monitored. For instance, you can\nstart a cotton program on a washer and get a notification when the cycle is\ncomplete.\n\nTo get started with this web client, visit https://developer.home-connect.com\nand register an account. An application with a client ID for this API client\nwill be automati[...]",
		"version": "1"
	},
	"host": "api.home-connect.com",
	"schemes": [
		"https"
	],
	"basePath": "/api",
	"tags": [
		{
			"name": "default",
			"description": "Enumerate your home appliances"
		},
		{
			"name": "programs",
			"description": "Start, monitor and stop programs"
		},
		{
			"name": "status_events",
			"description": "Monitor the status and events"
		},
		{
			"name": "images",
			"description": "Access the camera in the fridge"
		},
		{
			"name": "settings",
			"description": "Get and set settings"
		},
		{
			"name": "commands",
			"description": "Send commands"
		}
	],
	"paths": {
		"/homeappliances": {
			"get": {
				"summary": "Get all home appliances which are paired with the logged-in user account.",
				"operationId": "get_home_appliances",
				"description": "This endpoint returns a list of all home appliances which are paired\nwith the logged-in user account. All paired home appliances are returned\nindependent of their current connection state. The connection state can\nbe retrieved within the field 'connected' of the respective home appliance.\nThe haId is the primary access key for further API access to a specific\nhome appliance.\n",
				"security": [
					{
						"homeconnect_auth": [
							"IdentifyAppliance"
						]
					}
				]
			}
		},
		"/homeappliances/{haid}": {
			"get": {
				"summary": "Get a specfic home appliances which are paired with the logged-in user account.",
				"operationId": "get_specific_appliance",
				"description": "This endpoint returns a specific home appliance which is paired with the\nlogged-in user account. It is returned independent of their current\nconnection state. The connection state can be retrieved within the field\n'connected' of the respective home appliance.\nThe haId is the primary access key for further API access to a specific\nhome appliance.\n",
				"security": [
					{
						"homeconnect_auth": [
							"IdentifyAppliance"
						]
					}
				]
			}
		},
		"/homeappliances/{haid}/programs/active": {
			"get": {
				"summary": "Get program which is currently executed",
				"tags": [
					"programs"
				],
				"operationId": "get_active_program",
				"security": [
					{
						"homeconnect_auth": [
							"Monitor",
							"Oven-Monitor",
							"Dishwasher-Monitor",
							"Washer-Monitor",
							"Dryer-Monitor",
							"CoffeeMaker-Monitor",
							"Hob-Monitor",
							"Hood-Monitor",
							"CleaningRobot-Monitor",
							"Oven",
							"Dishwasher",
							"Washer",
							"Dryer",
							"CoffeeMaker",
							"Hob",
							"Hood",
							"CleaningRobot"
						]
					}
				]
			},
			"put": {
				"summary": "Start the given program",
				"tags": [
					"programs"
				],
				"operationId": "start_program",
				"description": "By putting a program object to this endpoint, the system will try to\nstart it if all preconditions are fulfilled:\n* Home appliance is connected\n* *Remote Control* and *Remote Control Start Allowed* is enabled\n* No other program is currently active\n\nFurthermore, the program must exist on the home appliance and its\noptions must be set correctly.\nKeys of program, which can be exected on an oven, are for instance:\n* *Cooking.Oven.Program.HeatingMode.HotAir*\n* *Cooking.O[...]",
				"security": [
					{
						"homeconnect_auth": [
							"Control",
							"Oven-Control",
							"Dishwasher-Control",
							"Washer-Control",
							"Dryer-Control",
							"CoffeeMaker-Control",
							"Hob-Control",
							"Hood-Control",
							"CleaningRobot-Control",
							"Oven",
							"Dishwasher",
							"Washer",
							"Dryer",
							"CoffeeMaker",
							"Hob",
							"Hood",
							"CleaningRobot"
						]
					}
				]
			},
			"delete": {
				"summary": "Stop the program which is currently executed",
				"tags": [
					"programs"
				],
				"operationId": "stop_program",
				"security": [
					{
						"homeconnect_auth": [
							"Control",
							"Oven-Control",
							"Dishwasher-Control",
							"Washer-Control",
							"Dryer-Control",
							"CoffeeMaker-Control",
							"Hob-Control",
							"Hood-Control",
							"CleaningRobot-Control",
							"Oven",
							"Dishwasher",
							"Washer",
							"Dryer",
							"CoffeeMaker",
							"Hob",
							"Hood",
							"CleaningRobot"
						]
					}
				]
			}
		},
		"/homeappliances/{haid}/programs/active/options": {
			"get": {
				"summary": "Get all options of the active program like temperature or duration.",
				"description": "You can retrieve a list of options of the currently running program.\n\nFor detailed documentation of the available options, visit the appliance-specific programs pages:\n* [Oven](https://developer.home-connect.com/docs/oven/supported_programs_and_options)\n* [Dishwasher](https://developer.home-connect.com/docs/dishwasher/supported_programs_options)\n* [Washer](https://developer.home-connect.com/docs/washing-machine/supported_programs_and_options)\n* [Dryer](https://developer[...]",
				"tags": [
					"programs"
				],
				"operationId": "get_active_program_options",
				"security": [
					{
						"homeconnect_auth": [
							"Monitor",
							"Oven-Monitor",
							"Dishwasher-Monitor",
							"Washer-Monitor",
							"Dryer-Monitor",
							"CoffeeMaker-Monitor",
							"Hob-Monitor",
							"Hood-Monitor",
							"CleaningRobot-Monitor",
							"Oven",
							"Dishwasher",
							"Washer",
							"Dryer",
							"CoffeeMaker",
							"Hob",
							"Hood",
							"CleaningRobot"
						]
					}
				]
			},
			"put": {
				"summary": "Set all options of the active program, e.g. to switch from preheating to the actual program options.",
				"description": "Update the options for the currently running program.\nWith this API endpoint, you have to provide all options with\ntheir new values. If you want to update only one option, you can use the\nendpoint specific to that option.\n\nPlease note that changing options of the running program is currently only\nsupported by ovens.\n",
				"tags": [
					"programs"
				],
				"operationId": "set_active_program_options",
				"security": [
					{
						"homeconnect_auth": [
							"Control",
							"Oven-Control",
							"Dishwasher-Control",
							"Washer-Control",
							"Dryer-Control",
							"CoffeeMaker-Control",
							"Hob-Control",
							"Hood-Control",
							"CleaningRobot-Control",
							"Oven",
							"Dishwasher",
							"Washer",
							"Dryer",
							"CoffeeMaker",
							"Hob",
							"Hood",
							"CleaningRobot"
						]
					}
				]
			}
		},
		"/homeappliances/{haid}/programs/active/options/{optionkey}": {
			"get": {
				"summary": "Get one specific option of the active program, e.g. the duration.",
				"tags": [
					"programs"
				],
				"operationId": "get_active_program_option",
				"security": [
					{
						"homeconnect_auth": [
							"Monitor",
							"Oven-Monitor",
							"Dishwasher-Monitor",
							"Washer-Monitor",
							"Dryer-Monitor",
							"CoffeeMaker-Monitor",
							"Hob-Monitor",
							"Hood-Monitor",
							"CleaningRobot-Monitor",
							"Oven",
							"Dishwasher",
							"Washer",
							"Dryer",
							"CoffeeMaker",
							"Hob",
							"Hood",
							"CleaningRobot"
						]
					}
				]
			},
			"put": {
				"summary": "Set one specific option of the active program",
				"description": "This operation can be used to modify one specific option of the active\nprogram, e.g. to extend the duration of the active program by\nanother 5 minutes.\n\nPlease note that changing options of the running program is currently only\nsupported by ovens.\n",
				"tags": [
					"programs"
				],
				"operationId": "set_active_program_option",
				"security": [
					{
						"homeconnect_auth": [
							"Control",
							"Oven-Control",
							"Dishwasher-Control",
							"Washer-Control",
							"Dryer-Control",
							"CoffeeMaker-Control",
							"Hob-Control",
							"Hood-Control",
							"CleaningRobot-Control",
							"Oven",
							"Dishwasher",
							"Washer",
							"Dryer",
							"CoffeeMaker",
							"Hob",
							"Hood",
							"CleaningRobot"
						]
					}
				]
			}
		},
		"/homeappliances/{haid}/programs/selected": {
			"get": {
				"summary": "Get the program which is currently selected\n",
				"description": "In most cases the selected program is the program which is currently\nshown on the display of the home appliance. This program can then be\nmanually adjusted or started on the home appliance itself.\n",
				"tags": [
					"programs"
				],
				"operationId": "get_selected_program",
				"security": [
					{
						"homeconnect_auth": [
							"Monitor",
							"Oven-Monitor",
							"Dishwasher-Monitor",
							"Washer-Monitor",
							"Dryer-Monitor",
							"CoffeeMaker-Monitor",
							"Hob-Monitor",
							"Hood-Monitor",
							"CleaningRobot-Monitor",
							"Oven",
							"Dishwasher",
							"Washer",
							"Dryer",
							"CoffeeMaker",
							"Hob",
							"Hood",
							"CleaningRobot"
						]
					}
				]
			},
			"put": {
				"summary": "Select a program",
				"description": "In most cases the selected program is the program which is currently\nshown on the display of the home appliance. This program can then be\nmanually adjusted or started on the home appliance itself.\n\nA selected program will not be started automatically. You don't have\nto set a program as selected first if you intend to start it via API -\nyou can set it directly as active program.\n\nSelecting a program will update the available options and constraints\ndirectly from the h[...]",
				"tags": [
					"programs"
				],
				"operationId": "set_selected_program",
				"security": [
					{
						"homeconnect_auth": [
							"Control",
							"Oven-Control",
							"Dishwasher-Control",
							"Washer-Control",
							"Dryer-Control",
							"CoffeeMaker-Control",
							"Hob-Control",
							"Hood-Control",
							"CleaningRobot-Control",
							"Oven",
							"Dishwasher",
							"Washer",
							"Dryer",
							"CoffeeMaker",
							"Hob",
							"Hood",
							"CleaningRobot"
						]
					}
				]
			}
		},
		"/homeappliances/{haid}/programs/selected/options": {
			"get": {
				"summary": "Get all options of selected program",
				"tags": [
					"programs"
				],
				"operationId": "get_selected_program_options",
				"security": [
					{
						"homeconnect_auth": [
							"Monitor",
							"Oven-Monitor",
							"Dishwasher-Monitor",
							"Washer-Monitor",
							"Dryer-Monitor",
							"CoffeeMaker-Monitor",
							"Hob-Monitor",
							"Hood-Monitor",
							"CleaningRobot-Monitor",
							"Oven",
							"Dishwasher",
							"Washer",
							"Dryer",
							"CoffeeMaker",
							"Hob",
							"Hood",
							"CleaningRobot"
						]
					}
				]
			},
			"put": {
				"summary": "Set all options of selected program",
				"tags": [
					"programs"
				],
				"operationId": "set_selected_program_options",
				"security": [
					{
						"homeconnect_auth": [
							"Control",
							"Oven-Control",
							"Dishwasher-Control",
							"Washer-Control",
							"Dryer-Control",
							"CoffeeMaker-Control",
							"Hob-Control",
							"Hood-Control",
							"CleaningRobot-Control",
							"Oven",
							"Dishwasher",
							"Washer",
							"Dryer",
							"CoffeeMaker",
							"Hob",
							"Hood",
							"CleaningRobot"
						]
					}
				]
			}
		},
		"/homeappliances/{haid}/programs/selected/options/{optionkey}": {
			"get": {
				"summary": "Get specific option of selected program",
				"tags": [
					"programs"
				],
				"operationId": "get_selected_program_option",
				"security": [
					{
						"homeconnect_auth": [
							"Monitor",
							"Oven-Monitor",
							"Dishwasher-Monitor",
							"Washer-Monitor",
							"Dryer-Monitor",
							"CoffeeMaker-Monitor",
							"Hob-Monitor",
							"Hood-Monitor",
							"CleaningRobot-Monitor",
							"Oven",
							"Dishwasher",
							"Washer",
							"Dryer",
							"CoffeeMaker",
							"Hob",
							"Hood",
							"CleaningRobot"
						]
					}
				]
			},
			"put": {
				"summary": "Set specific option of selected program",
				"tags": [
					"programs"
				],
				"operationId": "set_selected_program_option",
				"security": [
					{
						"homeconnect_auth": [
							"Control",
							"Oven-Control",
							"Dishwasher-Control",
							"Washer-Control",
							"Dryer-Control",
							"CoffeeMaker-Control",
							"Hob-Control",
							"Hood-Control",
							"CleaningRobot-Control",
							"Oven",
							"Dishwasher",
							"Washer",
							"Dryer",
							"CoffeeMaker",
							"Hob",
							"Hood",
							"CleaningRobot"
						]
					}
				]
			}
		},
		"/homeappliances/{haid}/programs/available": {
			"get": {
				"summary": "Get all programs which are currently available on the given home appliance",
				"tags": [
					"programs"
				],
				"operationId": "get_available_programs",
				"security": [
					{
						"homeconnect_auth": [
							"Monitor",
							"Oven-Monitor",
							"Dishwasher-Monitor",
							"Washer-Monitor",
							"Dryer-Monitor",
							"CoffeeMaker-Monitor",
							"Hob-Monitor",
							"Hood-Monitor",
							"CleaningRobot-Monitor",
							"Oven",
							"Dishwasher",
							"Washer",
							"Dryer",
							"CoffeeMaker",
							"Hob",
							"Hood",
							"CleaningRobot"
						]
					}
				]
			}
		},
		"/homeappliances/{haid}/programs/available/{programkey}": {
			"get": {
				"summary": "Get specific available program",
				"tags": [
					"programs"
				],
				"operationId": "get_available_program",
				"security": [
					{
						"homeconnect_auth": [
							"Monitor",
							"Oven-Monitor",
							"Dishwasher-Monitor",
							"Washer-Monitor",
							"Dryer-Monitor",
							"CoffeeMaker-Monitor",
							"Hob-Monitor",
							"Hood-Monitor",
							"CleaningRobot-Monitor",
							"Oven",
							"Dishwasher",
							"Washer",
							"Dryer",
							"CoffeeMaker",
							"Hob",
							"Hood",
							"CleaningRobot"
						]
					}
				]
			}
		},
		"/homeappliances/{haid}/images": {
			"get": {
				"summary": "Get a list of available images",
				"tags": [
					"images"
				],
				"operationId": "get_images",
				"security": [
					{
						"homeconnect_auth": [
							"Images",
							"FridgeFreezer-Images",
							"FridgeFreezer"
						]
					}
				]
			}
		},
		"/homeappliances/{haid}/images/{imagekey}": {
			"get": {
				"summary": "Get a specific image",
				"tags": [
					"images"
				],
				"operationId": "get_image",
				"security": [
					{
						"homeconnect_auth": [
							"Images",
							"FridgeFreezer-Images",
							"FridgeFreezer"
						]
					}
				]
			}
		},
		"/homeappliances/{haid}/settings": {
			"get": {
				"summary": "Get a list of available settings",
				"description": "Get a list of available setting of the home appliance.\n\nFurther documentation can be found here:\n* [Power state](https://developer.home-connect.com/docs/settings/power_state)\n* [Fridge temperature](https://developer.home-connect.com/docs/api/settings/fridgetemperature)\n* [Fridge super mode](https://developer.home-connect.com/docs/api/settings/fridgesupermode)\n* [Freezer temperature](https://developer.home-connect.com/docs/api/settings/freezertemperature)\n* [Freezer sup[...]",
				"tags": [
					"settings"
				],
				"operationId": "get_settings",
				"security": [
					{
						"homeconnect_auth": [
							"Settings",
							"Oven-Settings",
							"Dishwasher-Settings",
							"Washer-Settings",
							"Dryer-Settings",
							"FridgeFreezer-Settings",
							"CoffeeMaker-Settings",
							"Hob-Settings",
							"Hood-Settings",
							"CleaningRobot-Settings",
							"Oven",
							"Dishwasher",
							"Washer",
							"Dryer",
							"FridgeFreezer",
							"CoffeeMaker",
							"Hob",
							"Hood",
							"CleaningRobot"
						]
					}
				]
			}
		},
		"/homeappliances/{haid}/settings/{settingkey}": {
			"get": {
				"summary": "Get a specific setting",
				"tags": [
					"settings"
				],
				"operationId": "get_setting",
				"security": [
					{
						"homeconnect_auth": [
							"Settings",
							"Oven-Settings",
							"Dishwasher-Settings",
							"Washer-Settings",
							"Dryer-Settings",
							"FridgeFreezer-Settings",
							"CoffeeMaker-Settings",
							"Hob-Settings",
							"Hood-Settings",
							"CleaningRobot-Settings",
							"Oven",
							"Dishwasher",
							"Washer",
							"Dryer",
							"FridgeFreezer",
							"CoffeeMaker",
							"Hob",
							"Hood",
							"CleaningRobot"
						]
					}
				]
			},
			"put": {
				"summary": "Set a specific setting",
				"tags": [
					"settings"
				],
				"operationId": "set_setting",
				"security": [
					{
						"homeconnect_auth": [
							"Settings",
							"Oven-Settings",
							"Dishwasher-Settings",
							"Washer-Settings",
							"Dryer-Settings",
							"FridgeFreezer-Settings",
							"CoffeeMaker-Settings",
							"Hob-Settings",
							"Hood-Settings",
							"CleaningRobot-Settings",
							"Oven",
							"Dishwasher",
							"Washer",
							"Dryer",
							"FridgeFreezer",
							"CoffeeMaker",
							"Hob",
							"Hood",
							"CleaningRobot"
						]
					}
				]
			}
		},
		"/homeappliances/{haid}/status": {
			"get": {
				"summary": "Get current status of home appliance",
				"description": "A detailed description of the available status can be found here:\n\n* [Remote control activation state](https://developer.home-connect.com/docs/api/status/remotecontrolactivationstate)\n* [Remote start allowance state](https://developer.home-connect.com/docs/api/status/remotestartallowancestate)\n* [Local control state](https://developer.home-connect.com/docs/api/status/localcontrolstate)\n* [Operation state](https://developer.home-connect.com/docs/status/operation_state)\n*[...]",
				"tags": [
					"status_events"
				],
				"operationId": "get_status",
				"security": [
					{
						"homeconnect_auth": [
							"Monitor",
							"Oven-Monitor",
							"Dishwasher-Monitor",
							"Washer-Monitor",
							"Dryer-Monitor",
							"FridgeFreezer-Monitor",
							"CoffeeMaker-Monitor",
							"Hob-Monitor",
							"Hood-Monitor",
							"CleaningRobot-Monitor",
							"Oven",
							"Dishwasher",
							"Washer",
							"Dryer",
							"FridgeFreezer",
							"CoffeeMaker",
							"Hob",
							"Hood",
							"CleaningRobot"
						]
					}
				]
			}
		},
		"/homeappliances/{haid}/status/{statuskey}": {
			"get": {
				"summary": "Get current status of home appliance",
				"description": "A detailed description of the available status can be found here:\n\n* [Remote control activation state](https://developer.home-connect.com/docs/api/status/remotecontrolactivationstate)\n* [Remote start allowance state](https://developer.home-connect.com/docs/api/status/remotestartallowancestate)\n* [Local control state](https://developer.home-connect.com/docs/api/status/localcontrolstate)\n* [Operation state](https://developer.home-connect.com/docs/status/operation_state)\n*[...]",
				"tags": [
					"status_events"
				],
				"operationId": "get_status_value",
				"security": [
					{
						"homeconnect_auth": [
							"Monitor",
							"Oven-Monitor",
							"Dishwasher-Monitor",
							"Washer-Monitor",
							"Dryer-Monitor",
							"FridgeFreezer-Monitor",
							"CoffeeMaker-Monitor",
							"Hob-Monitor",
							"Hood-Monitor",
							"CleaningRobot-Monitor",
							"Oven",
							"Dishwasher",
							"Washer",
							"Dryer",
							"FridgeFreezer",
							"CoffeeMaker",
							"Hob",
							"Hood",
							"CleaningRobot"
						]
					}
				]
			}
		},
		"/homeappliances/{haid}/commands": {
			"get": {
				"summary": "Get a list of supported commands of the home appliance",
				"tags": [
					"commands"
				],
				"operationId": "get_available_commands",
				"security": [
					{
						"homeconnect_auth": [
							"Control",
							"Oven-Control",
							"Dishwasher-Control",
							"Washer-Control",
							"Dryer-Control",
							"CoffeeMaker-Control",
							"FridgeFreezer-Control",
							"Hob-Control",
							"Hood-Control",
							"CleaningRobot-Control",
							"Oven",
							"Dishwasher",
							"Washer",
							"Dryer",
							"CoffeeMaker",
							"FridgeFreezer",
							"Hob",
							"Hood",
							"CleaningRobot"
						]
					}
				]
			}
		},
		"/homeappliances/{haid}/commands/{commandkey}": {
			"put": {
				"summary": "Execute a specific command of the home appliance",
				"tags": [
					"commands"
				],
				"operationId": "put_command",
				"security": [
					{
						"homeconnect_auth": [
							"Control",
							"Oven-Control",
							"Dishwasher-Control",
							"Washer-Control",
							"Dryer-Control",
							"CoffeeMaker-Control",
							"FridgeFreezer-Control",
							"Hob-Control",
							"Hood-Control",
							"CleaningRobot-Control",
							"Oven",
							"Dishwasher",
							"Washer",
							"Dryer",
							"CoffeeMaker",
							"FridgeFreezer",
							"Hob",
							"Hood",
							"CleaningRobot"
						]
					}
				]
			}
		},
		"/homeappliances/{haid}/events": {
			"get": {
				"summary": "Get stream of events for one appliance - NOT WORKING WITH SWAGGER",
				"tags": [
					"status_events"
				],
				"operationId": "get_events",
				"description": "Server Sent Events are available as Eventsource API in JavaScript\nand are implemented by various HTTP client libraries and tools\nincluding curl.\n\nUnfortunately, SSE is not compatible to OpenAPI specs and can therefore\nnot be properly specified within this API description.\n\nAn SSE event contains three parts separated by linebreaks: event, data and id.\nDifferent events are separated by empty lines.\n\nThe event field can be one of these types: KEEP-ALIVE, STATUS, EVENT,[...]",
				"security": [
					{
						"homeconnect_auth": [
							"Monitor",
							"Oven-Monitor",
							"Dishwasher-Monitor",
							"Washer-Monitor",
							"Dryer-Monitor",
							"FridgeFreezer-Monitor",
							"CoffeeMaker-Monitor",
							"Hob-Monitor",
							"Hood-Monitor",
							"CleaningRobot-Monitor",
							"Oven",
							"Dishwasher",
							"Washer",
							"Dryer",
							"FridgeFreezer",
							"CoffeeMaker",
							"Hob",
							"Hood",
							"CleaningRobot"
						]
					}
				]
			}
		},
		"/homeappliances/events": {
			"get": {
				"summary": "Get stream of events for all appliances - NOT WORKING WITH SWAGGER",
				"tags": [
					"status_events"
				],
				"operationId": "get_all_events",
				"description": "Server Sent Events are available as Eventsource API in JavaScript\nand are implemented by various HTTP client libraries and tools\nincluding curl.\n\nUnfortunately, SSE is not compatible to OpenAPI specs and can therefore\nnot be properly specified within this API description.\n\nAn SSE event contains three parts separated by linebreaks: event, data and id.\nDifferent events are separated by empty lines.\n\nThe event field can be one of these types: KEEP-ALIVE, STATUS, EVENT,[...]",
				"security": [
					{
						"homeconnect_auth": [
							"Monitor",
							"Oven-Monitor",
							"Dishwasher-Monitor",
							"Washer-Monitor",
							"Dryer-Monitor",
							"FridgeFreezer-Monitor",
							"CoffeeMaker-Monitor",
							"Hob-Monitor",
							"Hood-Monitor",
							"CleaningRobot-Monitor",
							"Oven",
							"Dishwasher",
							"Washer",
							"Dryer",
							"FridgeFreezer",
							"CoffeeMaker",
							"Hob",
							"Hood",
							"CleaningRobot"
						]
					}
				]
			}
		}
	},
	"securityDefinitions": {
		"homeconnect_auth": {
			"description": "The Home Connect API uses the authorization code grant flow of the OAuth2\nAuthorization Framework as specified in RFC 6749 (https://tools.ietf.org/html/rfc6749).\nAuthorization tokens have to be transmitted in the HTTP headers as defined\nin RFC 6750 (https://tools.ietf.org/html/rfc6750).\n",
			"type": "oauth2",
			"flow": "accessCode",
			"authorizationUrl": "https://api.home-connect.com/security/oauth/authorize",
			"tokenUrl": "https://api.home-connect.com/security/oauth/token",
			"x-homeconnect-revokeUrl": "https://api.home-connect.com/security/oauth/revoke",
			"scopes": {
				"IdentifyAppliance": "Grants right to identify a home appliance under /api/homeappliances",
				"Monitor": "Grants access to read resources under /api/homeappliances except images and settings",
				"Control": "Grants access to modify resources under under /api/homeappliances except images and settings",
				"Images": "Grants access to read resources under /api/homeappliances/{haid}/images",
				"Settings": "Grants access to read and modify resources under /api/homeappliances/{haid}/settings",
				"Oven-Monitor": "Grants access to read resources under /api/homeappliances except images and settings on ovens",
				"Oven-Control": "Grants access to modify resources under under /api/homeappliances except images and settings on ovens",
				"Oven-Settings": "Grants access to read and modify resources under /api/homeappliances/{haid}/settings on ovens",
				"Oven": "Grants access to read or modify all resources under /api/homeappliances on ovens",
				"Dishwasher-Monitor": "Grants access to read resources under /api/homeappliances except images and settings on dishwashers",
				"Dishwasher-Control": "Grants access to modify resources under under /api/homeappliances except images and settings on dishwashers",
				"Dishwasher-Settings": "Grants access to read and modify resources under /api/homeappliances/{haid}/settings on dishwashers",
				"Dishwasher": "Grants access to read or modify all resources under /api/homeappliances on dishwashers",
				"Washer-Monitor": "Grants access to read resources under /api/homeappliances except images and settings on washers",
				"Washer-Control": "Grants access to modify resources under under /api/homeappliances except images and settings on washers",
				"Washer-Settings": "Grants access to read and modify resources under /api/homeappliances/{haid}/settings on washers",
				"Washer": "Grants access to read or modify all resources under /api/homeappliances on washers",
				"Dryer-Monitor": "Grants access to read resources under /api/homeappliances except images and settings on dryers",
				"Dryer-Control": "Grants access to modify resources under under /api/homeappliances except images and settings on dryers",
				"Dryer-Settings": "Grants access to read and modify resources under /api/homeappliances/{haid}/settings on dryers",
				"Dryer": "Grants access to read or modify all resources under /api/homeappliances on dryers",
				"FridgeFreezer-Monitor": "Grants access to read resources under /api/homeappliances except images and settings on fridgefreezers",
				"FridgeFreezer-Control": "Grants access to modify resources under /api/homeappliances except images and settings on fridgefreezers",
				"FridgeFreezer-Settings": "Grants access to read and modify resources under /api/homeappliances/{haid}/settings on fridgefreezers",
				"FridgeFreezer-Images": "Grants access to read resources under /api/homeappliances/{haid}/images on fridgefreezers",
				"FridgeFreezer": "Grants access to read or modify all resources under /api/homeappliances on fridgefreezers",
				"CoffeeMaker-Monitor": "Grants access to read resources under /api/homeappliances except images and settings on coffee makers",
				"CoffeeMaker-Control": "Grants access to modify resources under under /api/homeappliances except images and settings on coffee makers",
				"CoffeeMaker-Settings": "Grants access to read and modify resources under /api/homeappliances/{haid}/settings on coffee makers",
				"CoffeeMaker": "Grants access to read or modify all resources under /api/homeappliances on coffeemakers",
				"Hob-Monitor": "Grants access to read resources under /api/homeappliances except images and settings on coffee makers",
				"Hob-Control": "Grants access to modify resources under under /api/homeappliances except images and settings on coffee makers",
				"Hob-Settings": "Grants access to read and modify resources under /api/homeappliances/{haid}/settings on coffee makers",
				"Hob": "Grants access to read or modify all resources under /api/homeappliances on coffeemakers",
				"Hood-Monitor": "Grants access to read resources under /api/homeappliances except images and settings on coffee makers",
				"Hood-Control": "Grants access to modify resources under under /api/homeappliances except images and settings on coffee makers",
				"Hood-Settings": "Grants access to read and modify resources under /api/homeappliances/{haid}/settings on coffee makers",
				"Hood": "Grants access to read or modify all resources under /api/homeappliances on coffeemakers",
				"CleaningRobot-Monitor": "Grants access to read resources under /api/homeappliances except images and settings on coffee makers",
				"CleaningRobot-Control": "Grants access to modify resources under under /api/homeappliances except images and settings on coffee makers",
				"CleaningRobot-Settings": "Grants access to read and modify resources under /api/homeappliances/{haid}/settings on coffee makers",
				"CleaningRobot": "Grants access to read or modify all resources under /api/homeappliances on coffeemakers"
			}
		}
	}
}
